version: '2'
services:
  redis:
    image: redis:3.2.0-alpine
    volumes:
      - redis:/data
    restart: always
    command: "redis-server --appendonly yes"
  nepeatbot:
      build: .
      restart: always
      environment:
        REDIS_HOST: redis
        REDIS_PORT: 6379
      env_file: .env
      depends_on:
        - redis
volumes:
  redis:
    driver: local