version: '2.3'
services:
  redis:
    image: redis:4.0.8-alpine
    volumes:
      - /mnt/nfs/discordbot/redis:/data
    restart: always
    command: "redis-server --appendonly yes"
    environment:
      SERVICE_NAME: discordbot_redis
    expose:
      - 6379
    network_mode: bridge
    dns: "172.17.0.1"

  bot:
      image: registry.gitlab.com/nepeat1/homura-discord/bot:latest
      restart: always
      environment:
        REDIS_HOST: discordbot_redis.dev01.docker
        REDIS_PORT: 6379
        BOT_WEB: http://discordbot_backend.dev01.docker:5000
        AUDIO_CACHE_PATH: /audio_cache

        # Shared app secrets.
        DISCORD_TOKEN: ${PROD_DISCORD_TOKEN}
        DISCORD_CLIENT_ID: ${PROD_DISCORD_CLIENT_ID}
        DISCORD_CLIENT_SECRET: ${PROD_DISCORD_CLIENT_SECRET}
        SENTRY_DSN: ${SENTRY_DSN}
        POSTGRES_URL: ${PROD_POSTGRES_URL}
        APP_SECRET: ${APP_SECRET}
        INFLUX_HOST: ${INFLUX_HOST}
        OSU_API: ${OSU_API}
        IMGUR_ID: ${IMGUR_ID}
        MASHAPE_KEY: ${MASHAPE_KEY}
        
      read_only: true
      tmpfs:
        - /run
        - /tmp
      volumes:
        - /mnt/nfs/discordbot/audio_cache:/audio_cache
      env_file: .env
      depends_on:
        - redis
        - backend
      network_mode: bridge
      dns: "172.17.0.1"

  backend:
      image: registry.gitlab.com/nepeat1/homura-discord/backend:latest
      restart: always
      environment:
        REDIS_HOST: discordbot_redis.dev01.docker
        REDIS_PORT: 6379
        SERVICE_NAME: discordbot_backend

        # Shared app secrets.
        DISCORD_TOKEN: ${PROD_DISCORD_TOKEN}
        DISCORD_CLIENT_ID: ${PROD_DISCORD_CLIENT_ID}
        DISCORD_CLIENT_SECRET: ${PROD_DISCORD_CLIENT_SECRET}
        SENTRY_DSN: ${SENTRY_DSN}
        POSTGRES_URL: ${PROD_POSTGRES_URL}
        APP_SECRET: ${APP_SECRET}
        INFLUX_HOST: ${INFLUX_HOST}
        OSU_API: ${OSU_API}
        IMGUR_ID: ${IMGUR_ID}
        MASHAPE_KEY: ${MASHAPE_KEY}
      read_only: true
      tmpfs:
        - /run
        - /tmp
      env_file: .env
      depends_on:
        - redis
      network_mode: bridge
      dns: "172.17.0.1"
