version: '2'
services:
  redis:
    image: redis:3.2.9-alpine
    volumes:
      - redis:/data
    restart: always
    command: "redis-server --appendonly yes"

  bot:
      build:
          context: bot
      restart: always
      environment:
        REDIS_HOST: redis
        REDIS_PORT: 6379
        BOT_WEB: http://backend:5000
        AUDIO_CACHE_PATH: /audio_cache
      read_only: true
      tmpfs:
        - /run
        - /tmp
      volumes:
        - audio_cache:/audio_cache
      env_file: .env
      depends_on:
        - redis
        - backend

  backend:
      build:
          context: backend
      restart: always
      environment:
        REDIS_HOST: redis
        REDIS_PORT: 6379
      read_only: true
      tmpfs:
        - /run
        - /tmp
      env_file: .env
      depends_on:
        - redis
volumes:
  redis:
    driver: local
  audio_cache:
    driver: local
