version: '2.3'
services:
  redis:
    image: redis:4.0.2-alpine
    volumes:
      - /mnt/nfs/discordbot/redis:/data
    restart: always
    command: "redis-server --appendonly yes"
    environment:
      SERVICE_NAME: discordbot_redis
    expose:
      - 6379
    network_mode: bridge
    dns: "172.17.0.1"

  bot:
      build:
          context: bot
      restart: always
      environment:
        REDIS_HOST: discordbot_redis.dev01.docker
        REDIS_PORT: 6379
        BOT_WEB: http://discordbot_backend.dev01.docker:5000
        AUDIO_CACHE_PATH: /audio_cache
      read_only: true
      tmpfs:
        - /run
        - /tmp
      volumes:
        - /mnt/nfs/discordbot/audio_cache:/audio_cache
      env_file: .env
      depends_on:
        - redis
        - backend
      network_mode: bridge
      dns: "172.17.0.1"

  backend:
      build:
          context: backend
      restart: always
      environment:
        REDIS_HOST: discordbot_redis.dev01.docker
        REDIS_PORT: 6379
        SERVICE_NAME: discordbot_backend
      read_only: true
      tmpfs:
        - /run
        - /tmp
      env_file: .env
      depends_on:
        - redis
      network_mode: bridge
      dns: "172.17.0.1"
