apiVersion: v1
kind: Namespace
metadata:
  name: homura-discord
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: homura-discord
spec:
  clusterIP: None
  ports:
  - name: backend
    port: 5000
    targetPort: 5000
  selector:
    app: backend
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: homura-discord
spec:
  clusterIP: None
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    app: redis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
  namespace: homura-discord
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:4.0.8-alpine
        command: ["redis-server", "--appendonly", "yes"]
        volumeMounts:
        - mountPath: /data
          name: redis-data
        ports:
        - containerPort: 6379
      restartPolicy: Always
      volumes:
        - name: redis-data
          hostPath:
            path: /mnt/nfs/discordbot/redis
            type: DirectoryOrCreate
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
  namespace: homura-discord
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: registry.gitlab.com/nepeat1/homura-discord/backend:latest
        env:
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        envFrom:
        - secretRef:
            name: homura-secrets
        ports:
        - containerPort: 5000
      restartPolicy: Always
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: bot
  name: bot
  namespace: homura-discord
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
      - name: bot
        image: registry.gitlab.com/nepeat1/homura-discord/bot:latest
        volumeMounts:
        - mountPath: /audio_cache
          name: audio-cache
        env:
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: BOT_WEB
          value: http://backend:5000
        - name: AUDIO_CACHE_PATH
          value: /audio_cache
        envFrom:
        - secretRef:
            name: homura-secrets
        ports:
        - containerPort: 6379
      restartPolicy: Always
      volumes:
        - name: audio-cache
          hostPath:
            path: /mnt/nfs/discordbot/audio_cache
            type: DirectoryOrCreate
