from nepeatbot.plugins.plugin_moderation import ModerationPlugin
from nepeatbot.plugins.plugin_quotes import QuotesPlugin
from nepeatbot.plugins.plugin_serverlog import ServerLogPlugin
from nepeatbot.plugins.plugin_botmanage import BotManagerPlugin
