"""created/edited times

Revision ID: 0c882e751079
Revises: 66db58c699e1
Create Date: 2019-02-16 09:30:40.405831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c882e751079'
down_revision = '66db58c699e1'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('messages', sa.Column('edited', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'edited')
    op.drop_column('messages', 'created')
    # ### end Alembic commands ###
