"""channel

Revision ID: 29c2a7faa00b
Revises: 
Create Date: 2016-11-08 18:51:32.540238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c2a7faa00b'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'channel',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'channel',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###
