"""channel, server name

Revision ID: 623e28955744
Revises: b12e91c607d7
Create Date: 2016-11-09 21:46:23.801187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '623e28955744'
down_revision = 'b12e91c607d7'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('name', sa.Unicode(length=100), nullable=True))
    op.add_column('servers', sa.Column('name', sa.Unicode(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'name')
    op.drop_column('channels', 'name')
    ### end Alembic commands ###
