"""reactions embed tts message

Revision ID: 66db58c699e1
Revises: ad6b6f2c3fd5
Create Date: 2019-02-16 05:25:52.347648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '66db58c699e1'
down_revision = 'ad6b6f2c3fd5'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('embeds', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('messages', sa.Column('reactions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('messages', sa.Column('tts', sa.Boolean(), server_default='f', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'tts')
    op.drop_column('messages', 'reactions')
    op.drop_column('messages', 'embeds')
    # ### end Alembic commands ###
