"""unique server and channel

Revision ID: ad6b6f2c3fd5
Revises: 588d317c3eac
Create Date: 2018-03-18 17:05:09.444122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad6b6f2c3fd5'
down_revision = '588d317c3eac'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'channels', ['channel_id'])
    op.create_unique_constraint(None, 'servers', ['server_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'servers', type_='unique')
    op.drop_constraint(None, 'channels', type_='unique')
    # ### end Alembic commands ###
